-- Joining a yard is invite only.
--
-- Two ways in, both of which mean the yard chose to let you in:
--   1. an emailed invite, one token, one use
--   2. the yard's standing join code, which is what a QR code in the
--      tack room encodes
--
-- Nobody can ask to join off their own bat any more, so the
-- request-to-join policy goes, and with it the only route by which a
-- stranger could insert their own membership row.

-- ── no more asking ──────────────────────────────────────────────
drop policy if exists membership_request_join on public.membership;

alter table public.business drop column if exists join_policy;
drop type if exists join_policy;

-- ── the yard's standing code ────────────────────────────────────
-- Hex, so there are no letters that get misread when somebody types it
-- off a poster instead of scanning it.
create or replace function private.new_join_code()
returns text
language sql
volatile
set search_path = ''
as $$
  select substr(replace(gen_random_uuid()::text, '-', ''), 1, 12);
$$;

alter table public.business
  add column if not exists join_code text unique;

update public.business
   set join_code = private.new_join_code()
 where join_code is null;

alter table public.business
  alter column join_code set not null,
  alter column join_code set default private.new_join_code();

-- The code is a credential, so an admin must not be able to choose it.
-- 0012 already narrowed this grant; this keeps join_code out of it.
revoke update on public.business from authenticated;
grant update (name, timezone) on public.business to authenticated;

-- Nobody may read another yard's code, and reading your own happens
-- through the admin screens, which select the business row anyway.
create or replace function public.rotate_join_code(p_business_id uuid)
returns text
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_code text;
begin
  if not private.is_admin_of(p_business_id) then
    raise exception 'not yours' using errcode = '42501';
  end if;

  v_code := private.new_join_code();
  update public.business set join_code = v_code where id = p_business_id;
  return v_code;
end;
$$;

revoke all on function public.rotate_join_code(uuid) from public;
grant execute on function public.rotate_join_code(uuid) to authenticated;

-- ── emailed invites ─────────────────────────────────────────────
create table public.invite (
  id           uuid primary key default gen_random_uuid(),
  business_id  uuid not null references public.business(id) on delete cascade,
  email        text not null,
  token        text not null unique default replace(gen_random_uuid()::text, '-', ''),
  invited_by   uuid references auth.users(id) on delete set null,
  created_at   timestamptz not null default now(),
  expires_at   timestamptz not null default now() + interval '30 days',
  accepted_at  timestamptz,
  accepted_by  uuid references auth.users(id) on delete set null,

  constraint invite_email_shape check (position('@' in email) > 1)
);

create index invite_business_idx on public.invite (business_id, created_at desc);

alter table public.invite enable row level security;

-- Only the yard sees or writes its own invites. The person accepting
-- one never reads this table; join_yard() does that for them.
create policy invite_admin_manages on public.invite
  for all to authenticated
  using (private.is_admin_of(business_id))
  with check (private.is_admin_of(business_id));

-- The token is generated by the default, not chosen by the caller.
revoke insert on public.invite from authenticated;
grant insert (business_id, email, invited_by) on public.invite to authenticated;

-- ── accepting either one ────────────────────────────────────────
create or replace function public.join_yard(p_token text)
returns table (business_id uuid, name text)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user uuid := auth.uid();
  v_biz  uuid;
  v_inv  uuid;
begin
  if v_user is null then
    raise exception 'sign in first' using errcode = '28000';
  end if;

  -- An emailed invite first, since it is the more specific of the two.
  select i.id, i.business_id into v_inv, v_biz
  from public.invite i
  where i.token = p_token
    and i.accepted_at is null
    and i.expires_at > now()
  for update;

  if v_biz is null then
    select b.id into v_biz
    from public.business b
    where b.join_code = p_token
      and b.status = 'active';
  end if;

  if v_biz is null then
    raise exception 'that link is not valid' using errcode = 'PT404';
  end if;

  -- do nothing on conflict, so somebody the yard has blocked cannot
  -- scan the poster again and undo it
  insert into public.membership (business_id, user_id, role, status, approved_at)
  values (v_biz, v_user, 'rider', 'approved', now())
  on conflict (business_id, user_id) do nothing;

  if v_inv is not null then
    update public.invite
       set accepted_at = now(), accepted_by = v_user
     where id = v_inv;
  end if;

  return query select b.id, b.name from public.business b where b.id = v_biz;
end;
$$;

revoke all on function public.join_yard(text) from public;
grant execute on function public.join_yard(text) to authenticated;
